### ISSUE TITLE
Error loading shared library ld-linux-x86-64.so.2: No such file or directory

### ISSUE THREAD

**Issue by radzikowskikacper** [BowellSolutions/bowell-frontend#19]
# OS
OS: Ubuntu 20.04.2 LTS
Docker version 20.10.12, build e91ed57
Docker Compose version v2.2.2

# Steps to reproduce:
1. Pasted 
```
API_URL=http://127.0.0.1:8000/api
API_ACCESS_TOKEN_LIFETIME=3600
```
into .env.local

2. Ran `docker-compose up --build` (branch `develop`)

# Expected
Frontend running in the container

# Got
```
[4/4] Building fresh packages...
Done in 79.72s.
 ---> 91ebe51782a0
Step 7/9 : COPY . .
 ---> ce68805e8bb2
Step 8/9 : EXPOSE 3000
 ---> Running in 7491575a85e3
 ---> 8129225cf444
Step 9/9 : CMD ["yarn", "dev"]
 ---> Running in 4c5ed7aa6e7f
 ---> 0b1eff0a6036
Successfully built 0b1eff0a6036
Successfully tagged bowel-frontend_frontend:latest

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 2/2
 ⠿ Network bowel-frontend_default  Created                                                                        0.1s
 ⠿ Container frontend              Created                                                                        5.4s
Attaching to frontend
frontend  | yarn run v1.22.5
frontend  | $ next dev
frontend  | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
frontend  | info  - Loaded env from /usr/src/app/.env.local
frontend  | warn  - SWC minify beta enabled. https://nextjs.org/docs/messages/swc-minify-enabled
frontend  | Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/src/app/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node)
frontend  |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
frontend  |     at Module.load (internal/modules/cjs/loader.js:937:32)
frontend  |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
frontend  |     at Module.require (internal/modules/cjs/loader.js:961:19)
frontend  |     at require (internal/modules/cjs/helpers.js:92:18)
frontend  |     at Object.<anonymous> (/usr/src/app/node_modules/next/dist/build/swc/index.js:29:20)
frontend  |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
frontend  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
frontend  |     at Module.load (internal/modules/cjs/loader.js:937:32)
frontend  |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
frontend  | error - Failed to load SWC binary, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
frontend  | error Command failed with exit code 1.
frontend  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
frontend exited with code 1
```

@Alschn

**Comment by Alschn** [comment]
The issue is associated with a new, experimental Next JS feature added in version 12, to be precise [SWC](https://nextjs.org/docs/advanced-features/compiler) (Rust-based platform which enhances build process), which seems not to be working properly on Alpine Linux (which is our base docker image).

Building frontend image works on production because, I think, we turned off swcMinify feature in next.config.js. https://github.com/BowellSolutions/bowell-frontend/blob/c186292aecd7cf88b1d5674cd0cc5de3691b9410/next.config.js#L11

Since migration from Next 11 to 12, I stopped using docker-compose and sticked to `yarn dev`, `yarn build` etc. Apart from this issue, my justification for this is that development with docker takes more time because you need to rebuild your container everytime you install a package - which happens quite often on frontend.

As I mentioned, I am aware of this issue and we will mostly likely look into it, since Next 12 has been around for some time and some solutions might have emerged. This means that With Docker section in README.md is not up to date for now.

TLDR: For now use `yarn dev` or `yarn build` + `yarn start`. Issue is known and will mostly likely be resolved soon.

**Comment by Alschn** [comment]
Workaround is to create `.babelrc` file in project's directory with following content:
```json
{
  "presets": ["next/babel"]
}
```

This will disable SWC and use Babel (default transpiler) instead.

**Comment by radzikowskikacper** [comment]
Thx!
